import {
  beauty,
  fitness,
  homeComfort,
  kitchen,
  office,
  outdoor,
  pet,
  smartHome,
  tech,
  wardrobe,
} from "./constants.js";

export const bannerList = [
  {
    id: 1,
    image: homeComfort,
    title: "Home Comfort",
    subtitle: "Living Room",
    description: "Upgrade your space with cozy and stylish sofas",
  },
  {
    id: 2,
    image: tech,
    title: "Tech Gadgets",
    subtitle: "Electronics",
    description: "Discover the latest smartphones and smart accessories",
  },
  {
    id: 3,
    image: fitness,
    title: "Fitness Gear",
    subtitle: "Workout",
    description: "Equip your home gym with premium training essentials",
  },
  {
    id: 4,
    image: kitchen,
    title: "Kitchen Essentials",
    subtitle: "Cooking & Dining",
    description: "Elevate your culinary experience with pro-grade cookware",
  },
  {
    id: 5,
    image: outdoor,
    title: "Outdoor Adventure",
    subtitle: "Camping & Hiking",
    description: "Gear up for your next trip with durable outdoor equipment",
  },
  {
    id: 6,
    image: office,
    title: "Office Supplies",
    subtitle: "Workspace",
    description: "Boost your productivity with ergonomic desk accessories",
  },
  {
    id: 7,
    image: beauty,
    title: "Beauty & Care",
    subtitle: "Personal Care",
    description: "Rejuvenate your routine with top-rated skincare products",
  },
  {
    id: 8,
    image: wardrobe,
    title: "Wardrobe Basics",
    subtitle: "Apparel",
    description:
      "Refresh your daily style with versatile and comfortable clothing",
  },
  {
    id: 9,
    image: pet,
    title: "Pet Supplies",
    subtitle: "Pets",
    description: "Treat your furry friends to high-quality toys and treats",
  },
  {
    id: 10,
    image: smartHome,
    title: "Smart Home",
    subtitle: "Automation",
    description: "Control your environment seamlessly with intelligent devices",
  },
];
